/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentCanceledRouteImport } from './routes/payment-canceled'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'

const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCanceledRoute = PaymentCanceledRouteImport.update({
  id: '/payment-canceled',
  path: '/payment-canceled',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payment-canceled'
    | '/payment-success'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/payment-canceled'
    | '/payment-success'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/payment-canceled'
    | '/payment-success'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentCanceledRoute: typeof PaymentCanceledRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-canceled': {
      id: '/payment-canceled'
      path: '/payment-canceled'
      fullPath: '/payment-canceled'
      preLoaderRoute: typeof PaymentCanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentCanceledRoute: PaymentCanceledRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
